### ISSUE TITLE
Single directory and multiple files

### ISSUE THREAD

**Issue by MrVokia** [ajpauwels/pit-of-vipers#1]
Hi~
If my config file is placed like this:
```shell
config
├── app.toml
├── cache.toml
├── db.toml
├── email.toml
```

how can i use it?
@ajpauwels

**Comment by ajpauwels** [comment]
The `New` function takes any arbitrary array of vipers, signature below:

```golang
func New(vipers []*viper.Viper) (viperChannel chan *viper.Viper, errChannel chan error) {
```

So you can define four viper instances, each of which has the same config path but a different config name, and provide all of them to the `New` function.

**Comment by ajpauwels** [comment]
I've closed this issue with comment above. If you find that my comment does not resolve your issue, please feel free to re-open with further questions. Thank you!
