### ISSUE TITLE
Does it merge map as well?

### ISSUE THREAD

**Issue by jbek7** [ajpauwels/pit-of-vipers#6]
config.yaml
```
database:
  uri: my-uri
```

secret.yaml
```
database:
  password: my-secret
```

`vpCh, errCh := viperpit.NewFromPaths([]string{"./"}) ` is not merging the configs from the root.

**Comment by ajpauwels** [comment]
@jbek7 Apologies for the late answer.

What you're looking for is the `NewFromPathsAndGlob` function:
https://github.com/ajpauwels/pit-of-vipers/blob/6720c674e577a22e7c358fa4493c2be71ecd6d34/config.go#L59

If you provide just a path, it will look for files named "config.yaml" at those paths. With the glob function, you can provide a glob that is the pattern of what the config filenames at that path look like.

The lib uses filepath.Glob to get filenames from the glob, for ref: https://pkg.go.dev/path/filepath#Glob

So if, for example, you prefixed your secret file with `config-`, i.e. you'd have `config.yaml` and `config-secret.yaml`, you could then pass `config*.yaml` as your glob and get them all :)

I'm going to close this assuming that solves your issue; if it does not, please feel free to re-open and I'll see what I can do!
